CREATE TABLE blockchain.ipfs_nodemetrics (
    node_id TEXT PRIMARY KEY,
    miner_id TEXT,
    bandwidth_mbps BIGINT,
    current_storage_bytes BIGINT,
    total_storage_bytes BIGINT,
    geolocation TEXT,
    successful_pin_checks INT,
    total_pin_checks INT,
    storage_proof_time_ms INT,
    storage_growth_rate BIGINT,
    latency_ms INT,
    total_latency_ms BIGINT,
    total_times_latency_checked INT,
    avg_response_time_ms INT,
    peer_count INT,
    failed_challenges_count INT,
    successful_challenges INT,
    total_challenges INT,
    uptime_minutes INT,
    total_minutes INT,
    consecutive_reliable_days INT,
    recent_downtime_hours INT,
    is_sev_enabled BOOLEAN,
    ipfs_zfs_pool_size TEXT,
    ipfs_zfs_pool_alloc TEXT,
    ipfs_zfs_pool_free TEXT,
    ipfs_repo_size BIGINT,
    ipfs_storage_max BIGINT,
    cpu_model TEXT,
    cpu_cores INT,
    memory_mb BIGINT,
    free_memory_mb BIGINT,
    gpu_name TEXT,
    gpu_memory_mb INT,
    hypervisor_disk_type TEXT,
    vm_pool_disk_type TEXT,
    vm_count INT,
    disks JSONB,
    disk_info JSONB,
    zfs_info JSONB,
    raid_info JSONB,
    primary_network_interface JSONB,
    updated_at TIMESTAMP DEFAULT NOW()
); 