include:
  - docker/docker-compose.infrastructure.yml
  - docker/docker-compose.epoch-health-consumer.yml
  - docker/docker-compose.miner-health-consumer.yml
  - docker/docker-compose.file-assignment-consumer.yml
  - docker/docker-compose.pinning-request-consumer.yml
  - docker/docker-compose.registration-consumer.yml
  - docker/docker-compose.user-profile-consumer.yml
  - docker/docker-compose.user-profile-reconstruction-consumer.yml
  - docker/docker-compose.miner-profile-reconstruction-consumer.yml
  - docker/docker-compose.network-self-healing-consumer.yml
  - docker/docker-compose.node-metrics-consumer.yml