[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ipfs-service-validator"
version = "0.0.1"
description = "Validator for Hippius network"
readme = "README.md"
requires-python = ">=3.9,<3.10"
license = {text = "MIT"}
authors = [
    {name = "veggies", email = "veggies@hippius.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "asyncpg",
    "httpx",
    "python-dotenv",
    "pydantic",
    "pydantic-settings",
    "aiofiles",
    "substrate-interface",
    "websockets",
    "psutil",
    "python-dotenv",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "ruff",
    "pre-commit",
]
