apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-validator-config
data:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "substrate_fetcher"
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "admin"
  RABBITMQ_VHOST: "/"
  DATABASE_URL: "postgres://user:password@postgres-service:5432/substrate_fetcher?sslmode=disable"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq-service:5672/"
  IPFS_NODE_URL: "http://ipfs-service:5001"
  IPFS_GATEWAY_URL: "https://ipfs.io"
  NODE_URL: "wss://rpc.hippius.network"
  PYTHONUNBUFFERED: "1"
  WAIT_FOR_IPFS: "true"
  NODE_METRICS_HISTORY_BLOCKS: "10" 