apiVersion: batch/v1
kind: Job
metadata:
  name: miner-profile-reconstruction-processor
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: processor
        image: ipfs-service-validator:latest
        imagePullPolicy: Never
        command: ["python", "rabbitmq/miner_profile_reconstruction_processor.py"]
        envFrom:
        - configMapRef:
            name: ipfs-validator-config
        workingDir: /app
  backoffLimit: 3 